---
- name: Auditar Datastore
  hosts: esxi-01.pclinux.com
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Inyectar pyvmomi dentro del contenedor
      ansible.builtin.pip:
        name: pyvmomi
        state: present
        executable: /usr/bin/pip3
      delegate_to: localhost

    - name: Consultar metricas del Datastore
      community.vmware.vmware_datastore_info:
        hostname: "{{ ansible_host | default('192.168.1.220') }}"
        username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
      delegate_to: localhost
      register: metrica_datastore

    - name: Mostrar datos extraidos del Datastore
      ansible.builtin.debug:
        var: metrica_datastore
