---
- name: Encender Maquina Virtual
  hosts: esxi-01.pclinux.com
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Inyectar pyvmomi dentro del contenedor
      ansible.builtin.pip:
        name: pyvmomi
        state: present
        executable: /usr/bin/pip3
      delegate_to: localhost

    - name: Mandar senal ACPI de encendido
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ ansible_host | default('192.168.1.220') }}"
        username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        name: "Servidor_Aplicativo_01"
        state: powered-on
      delegate_to: localhost
